### ISSUE TITLE
Make weekly-rewards

### ISSUE THREAD

**Issue by SnageTheSnakeMage** [Glue-N-Wrench/GMTK2024#38]
Every in game week we should get new houses to build from or new bombs
 - Maybe we can offer a choice of 3 sets randomly?
We will need to keep track of what houses our waiting to be built

**Comment by ChmmrAvatar** [comment]
i thought the random set was supposed to be each day, as the main way to get houses

**Comment by SnageTheSnakeMage** [comment]
steves out so im not entirely sure i just took what he had as a draft here, but if it is it wont be hard to make it one or the other. so I will focus on that later

**Comment by SnageTheSnakeMage** [comment]
it is done, we can change how many days it takes to get a reward anytime, but currently it is set to every 2 days. I formatted it to look like you get houses in sets like 2x L & J shaped houses or 1 Mansion or 3 Bombs etc etc
Of course the specifics(like the amount of bombs or lumping together L&J) will probably change but Is the amount of homes bit good with yall or nah? if not I can change it anytime.
