### ISSUE TITLE
In-Game Volume Adjustment Not Working (Minor Issue)

### ISSUE THREAD

**Issue by HeroicGreenBean** [Glue-N-Wrench/GMTK2024#72]
Currently, the mute buttons and volume sliders in the pause/options menu don't actually affect the audio at all.

**Comment by SnageTheSnakeMage** [comment]
handling it 👍

**Comment by SnageTheSnakeMage** [comment]
audio options does work but since pausing pauses the music too it is a bit more difficult to tune to the sounds when you have started a game. Working on a fix for this

**Comment by pistolPeterson** [comment]
> audio options does work but since pausing pauses the music too it is a bit more difficult to tune to the sounds when you have started a game. Working on a fix for this

[process modes ](https://docs.godotengine.org/en/stable/tutorials/scripting/pausing_games.html#process-modes)  all I did was change the music player process mode to always and its working as intended. I do see an issue that I cannot press pause key (escape) to toggle pause, might be a separate bug
